### ISSUE TITLE
Permission denied when attempting to install realesrgan (Mac M1)

### ISSUE THREAD

**Issue by misspear** [drovp/upscale#2]
The solution to this is probably going to be very simple, but I'm a relative newbie and it's left me baffled.

I have two Macs (Macbook Air and Mac Mini) and a Windows self-built PC. When installing the Upscale plugin, everything went smoothly on Windows, however on both my Macs I get the following permission error:

<img width="557" alt="Error" src="https://user-images.githubusercontent.com/32820615/218076028-17c90832-60a0-456a-8b57-3fc0f57a3053.png">

As far as I know, I've given all relevant permissions to the app, and it's only this specific dependency that won't install, and only on MacOS. Can anyone shed any light on this?

Thanks in advance.

**Comment by tomasklaen** [comment]
Hm... this is just a load error, which suggests the dependency installed correctly.

Can you check the path in the screenshot and what's in there?

My guess is that 7zip library I'm using to extract the downloaded archive is not setting permissions to the extracted files correctly. If there are files in `@drovp/upscale/realesrgan` directory, try changing their permissions to something Drovp can access and reloading the dependency.

Upscale installs both realesrgan and waifu2x upscalers. Does the waifu2x have the same issue? Or it might be skipped because the 1st one failed, not sure now.

**Comment by tomasklaen** [comment]
upscale also depends on ffmpeg, did that install correctly?

**Comment by misspear** [comment]
I did wonder whether it was an access issue rather than an installation one! Everything in the directory was there. I tried setting permissions through the Mac interface and no dice, but using chmod in Terminal seems to have cured it. Thank you for your help.

**Comment by tomasklaen** [comment]
The issue was in how realesrgan is packaged. The macos archive doesn't contain information that the binary should be marked as executable upon extraction, so it was being extracted as a generic file.

@drovp/upscale 4.0.1 now has an installation step to manually mark it as executable after extraction, so this should be fixed.
