### ISSUE TITLE
Dependency loading error

### ISSUE THREAD

**Issue by phederal** [drovp/upscale#3]
**OS:** Windows 10 Pro 10.0.19045
**App:** 0.6.2 x64

Hi! I got this error when installing dependency "realesrgan":

```
Error: ENOENT: no such file or directory, open 'D:\Program Files\Drovp\userData\dependencies\@drovp\upscale\realesrgan\version.txt'
```

**Comment by tomasklaen** [comment]
Is this not an issue anymore?

In case it is, looking at the path, `userData` should never be inside `Program Files`, unless you downloaded a portable version of Drovp and placed it inside `Program Files` manually, which is weird, because that folder is meant for installed programs only.

There are permissions issues with modifying anything inside `Program Files`, so either install Drovp through an installer, in which case it'll place `userData` into your profile's `AppData`, or place the portable version somewhere Windows doesn't prevent people from modifying.
